# Build and tag using commit sha

steps:

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.', '-t', 'gcr.io/rbbt-350607/emrahtestimage:${COMMIT_SHA}', '-f', 'Dockerfile']


# Push the container image


- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/rbbt-350607/emrahtestimage:${COMMIT_SHA}']
# Create release in Google Cloud Deploy


- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
    [
      "deploy", "releases", "create", "rel-${SHORT_SHA}",
      "--delivery-pipeline", "emrahtest",
      "--region", "europe-west1",
      "--annotations", "commitId=${REVISION_ID}",
      "--images", "emrahtestimage=gcr.io/rbbt-350607/emrahtestimage:${COMMIT_SHA}"
    ]