#Delivery Pipeline for our clusters

apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: emrahtest
description: main application pipeline
serialPipeline:
  stages:
  - targetId: qsdev

---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: qsdev
description: development environment
gke:
 cluster:  projects/rbbt-350607/locations/europe-west1-b/clusters/rbbt-cls
executionConfigs:
- defaultPool:
    serviceAccount: 662318006874-compute@developer.gserviceaccount.com
  usages:
  - RENDER 
  - DEPLOY   
