apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: emrahtest
build:
  artifacts:
  - image: gcr.io/rbbt-350607/emrahtestimage
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - deployment.yaml